version: '3.3'

services:
  db:
    #ignore this stuff, this is for mysql, will probably remove later
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_data:/var/lib/mysql

#postgres
    #image: postgres
    #restart: always
    #environment:
    #  POSTGRES_USER: user
    #  POSTGRES_PASSWORD: password
    #  POSTGRES_DB: db
    #ports:
    #  - '5432:5432'
    #expose:
    #  - '5432'
    #volumes:
    #  - postgresql_data:/var/lib/postgresql
    

volumes:
  mysql_data: {}